import argparse

def commandLineArgs():
    parser = argparse.ArgumentParser(description='Process some integers.')
    parser.add_argument("--restrict-types",
                        dest="restrict_types",
                        default=False,
                        action="store_true")
    parser.add_argument("--test",
                        dest="test",
                        default=False,
                        help="True if we want to just test an existing model",
                        action="store_true")
    parser.add_argument("--limit-overfit",
                        dest="limit_overfit",
                        default=False,
                        action="store_true")
    parser.add_argument("--use-cuda",
                        dest="use_cuda",
                        default=False,
                        action="store_true")
    parser.add_argument("--verbose",
                        dest="verbose",
                        default=False,
                        action="store_true")
    parser.add_argument("--rnn-decode",
                        dest="rnn_decode",
                        default=False,
                        action="store_true")
    parser.add_argument("--batch-size",
                        dest="batch_size",
                        default=32,
                        type=int)
    parser.add_argument("--lr",
                        dest="lr",
                        default=0.001,
                        type=float)
    parser.add_argument("--weight-decay",
                        dest="weight_decay",
                        default=0.0,
                        type=float)
    parser.add_argument("--beta",
                        dest="beta",
                        default=0.0,
                        type=float)
    parser.add_argument("--epochs-per-replay",
                        dest="epochs_per_replay",
                        default=0,
                        type=int)
    parser.add_argument("--beam-width",
                        dest="beam_width",
                        default=128,
                        type=int)
    parser.add_argument("--epsilon",
                        dest="epsilon",
                        default=0.3,
                        type=float)
    parser.add_argument("--num-cpus",
                        dest="num_cpus",
                        default=1,
                        type=int)
    parser.add_argument("--num-cycles",
                        dest="num_cycles",
                        default=1,
                        type=int)
    parser.add_argument("--max-p-per-task",
                        dest="max_p_per_task",
                        # something >> number of distinct programs per tasks
                        default=1000000,
                        type=int)
    parser.add_argument("--seed",
                        dest="seed",
                        default=0,
                        type=int)
    parser.add_argument("--jumpstart",
                        dest="jumpstart",
                        default=False,
                        help="Whether to jumpstart by training on set of ground truth programs first",
                        action="store_true")
    parser.add_argument("--num-iter-beam-search",
                        dest="num_iter_beam_search",
                        default=1,
                        type=int)
    parser.add_argument("--num-epochs-start",
                        dest="num_epochs_start",
                        default=1,
                        type=int)
    parser.add_argument("--resume-iter",
                        dest="resume_iter",
                        default=0,
                        type=int)
    parser.add_argument("--test-decode-time",
                        dest="test_decode_time",
                        default=0,
                        type=int)
    parser.add_argument("--fixed-epoch-pretrain",
                        dest="fixed_epoch_pretrain",
                        default=0,
                        type=int)
    parser.add_argument("--preload-frontiers",
                        dest="preload_frontiers",
                        default=None,
                        type=str)
    parser.add_argument("--resume",
                        dest="resume",
                        default=None,
                        type=str)
    parser.add_argument("--no-nl",
                        dest="no_nl",
                        default=False,
                        help="Whether to condition on natural language description i.e. use NL as input to encoder",
                        action="store_true")
    parser.add_argument("--no-io",
                        dest="no_io",
                        default=False,
                        help="Whether to use IO as input to encoder",
                        action="store_true")
    args = vars(parser.parse_args())
    return args
